language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

node_js:
  - "4"

jdk:
  - oraclejdk7  # needed for local Neo4j 2.0+

env:
  global:
    - NEO4J_VERSION="3.0.6"
    - sequinus-api_io__neo4j__host=localhost
    - sequinus-api_io__neo4j__port=7687
    - sequinus-api_io__neo4j__user=neo4j
    - sequinus-api_io__neo4j__pass=neo4j

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  # install yarn
  - npm i -g npm@3
  - npm i -g yarn --cache-min 999999999
  

install:
  - time yarn

script:
- npm run lint
- npm run test

